export const REASON_CODES = [
  'high_amount',
  'velocity_spike',
  'repeated_failed_attempts',
  'new_account',
  'new_device',
  'cross_border_mismatch',
  'missing_device',
  'risky_payment_method',
  'manual_entry',
  'email_mismatch',
  'low_signal_profile',
] as const;

export const FIELD_NAMES = [
  'amount',
  'currency',
  'payment_method',
  'channel',
  'customer_id',
  'customer_email',
  'billing_country',
  'shipping_country',
  'ip_address',
  'device_id',
  'account_age_days',
  'transactions_last_24h',
  'failed_attempts_last_24h',
  'tx_count_1hour',
  'tx_count_24hour',
  'amount_velocity_1hour',
  'amount_velocity_24hour',
  'unique_ips_1hour',
  'unique_ips_24hour',
  'new_device',
  'known_devices_count',
  'device_fingerprint_confidence',
  'ip_country_code',
  'issuing_country_code',
  'ip_billing_country_mismatch',
  'bin_issuing_country_mismatch',
  'high_risk_bin',
  'ip_geo_high_risk',
] as const;

export const OPERATORS = [
  'gte',
  'gt',
  'lte',
  'lt',
  'eq',
  'neq',
  'in',
  'not_in',
  'is_missing',
  'field_mismatch',
] as const;

