"""describe_change

Revision ID: 2bfa4233eafe
Revises: 5b066720cf70
Create Date: 2026-07-19 11:33:37.356612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfa4233eafe'
down_revision: Union[str, Sequence[str], None] = '5b066720cf70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_case_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_case_status_id'), 'review_case_status', ['id'], unique=False)
    op.create_index(op.f('ix_review_case_status_name'), 'review_case_status', ['name'], unique=False)
    op.add_column('review_cases', sa.Column('status_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_review_cases_status'), table_name='review_cases')
    op.create_index(op.f('ix_review_cases_status_id'), 'review_cases', ['status_id'], unique=False)
    op.create_foreign_key(None, 'review_cases', 'review_case_status', ['status_id'], ['id'])
    op.drop_column('review_cases', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_cases', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review_cases', type_='foreignkey')
    op.drop_index(op.f('ix_review_cases_status_id'), table_name='review_cases')
    op.create_index(op.f('ix_review_cases_status'), 'review_cases', ['status'], unique=False)
    op.drop_column('review_cases', 'status_id')
    op.drop_index(op.f('ix_review_case_status_name'), table_name='review_case_status')
    op.drop_index(op.f('ix_review_case_status_id'), table_name='review_case_status')
    op.drop_table('review_case_status')
    # ### end Alembic commands ###
