"""initial_schema

Revision ID: 5b066720cf70
Revises: 
Create Date: 2026-07-19 10:58:15.409120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b066720cf70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_number', sa.String(length=10), nullable=False),
    sa.Column('card_brand', sa.String(length=50), nullable=True),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('card_category', sa.String(length=100), nullable=True),
    sa.Column('issuing_bank', sa.String(length=200), nullable=True),
    sa.Column('issuing_country_code', sa.String(length=2), nullable=True),
    sa.Column('issuing_country_name', sa.String(length=100), nullable=True),
    sa.Column('is_prepaid', sa.Boolean(), nullable=False),
    sa.Column('is_commercial', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bin_lookups_bin_number'), 'bin_lookups', ['bin_number'], unique=True)
    op.create_index(op.f('ix_bin_lookups_id'), 'bin_lookups', ['id'], unique=False)
    op.create_table('ip_geolocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_start', sa.String(length=45), nullable=False),
    sa.Column('ip_end', sa.String(length=45), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('isp', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_geolocations_country_code'), 'ip_geolocations', ['country_code'], unique=False)
    op.create_index(op.f('ix_ip_geolocations_id'), 'ip_geolocations', ['id'], unique=False)
    op.create_index(op.f('ix_ip_geolocations_ip_end'), 'ip_geolocations', ['ip_end'], unique=False)
    op.create_index(op.f('ix_ip_geolocations_ip_start'), 'ip_geolocations', ['ip_start'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_index(op.f('ix_organisations_slug'), 'organisations', ['slug'], unique=True)
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_table('billing_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billing_interval', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_plans_id'), 'billing_plans', ['id'], unique=False)
    op.create_index(op.f('ix_billing_plans_organisation_id'), 'billing_plans', ['organisation_id'], unique=False)
    op.create_table('fraud_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('comparison_value', sa.JSON(), nullable=True),
    sa.Column('secondary_field_name', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_rules_enabled'), 'fraud_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_fraud_rules_field_name'), 'fraud_rules', ['field_name'], unique=False)
    op.create_index(op.f('ix_fraud_rules_id'), 'fraud_rules', ['id'], unique=False)
    op.create_index(op.f('ix_fraud_rules_operator'), 'fraud_rules', ['operator'], unique=False)
    op.create_index(op.f('ix_fraud_rules_organisation_id'), 'fraud_rules', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_fraud_rules_priority'), 'fraud_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_fraud_rules_reason_code'), 'fraud_rules', ['reason_code'], unique=False)
    op.create_index(op.f('ix_fraud_rules_rule_code'), 'fraud_rules', ['rule_code'], unique=False)
    op.create_table('organisation_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('review_threshold', sa.Integer(), nullable=False),
    sa.Column('decline_threshold', sa.Integer(), nullable=False),
    sa.Column('enable_billing', sa.Boolean(), nullable=False),
    sa.Column('enable_usage_tracking', sa.Boolean(), nullable=False),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_settings_id'), 'organisation_settings', ['id'], unique=False)
    op.create_index(op.f('ix_organisation_settings_organisation_id'), 'organisation_settings', ['organisation_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_type', sa.String(length=20), nullable=False),
    sa.Column('mfa_last_bound_at', sa.DateTime(), nullable=True),
    sa.Column('mfa_backup_codes_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_lookup', 'audit_logs', ['organisation_id', 'event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organisation_id'), 'audit_logs', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('billing_country', sa.String(length=2), nullable=True),
    sa.Column('shipping_country', sa.String(length=2), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('account_age_days', sa.Integer(), nullable=True),
    sa.Column('transactions_last_24h', sa.Integer(), nullable=False),
    sa.Column('failed_attempts_last_24h', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_channel'), 'transactions', ['channel'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_currency'), 'transactions', ['currency'], unique=False)
    op.create_index(op.f('ix_transactions_customer_email'), 'transactions', ['customer_email'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_transaction_id'), 'transactions', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_organisation_id'), 'transactions', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_transactions_payment_method'), 'transactions', ['payment_method'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('unit_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('billed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_event_type'), 'usage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_events_id'), 'usage_events', ['id'], unique=False)
    op.create_index(op.f('ix_usage_events_organisation_id'), 'usage_events', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    op.create_table('usage_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('limit_type', sa.String(length=50), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_limits_id'), 'usage_limits', ['id'], unique=False)
    op.create_index(op.f('ix_usage_limits_limit_type'), 'usage_limits', ['limit_type'], unique=False)
    op.create_index(op.f('ix_usage_limits_organisation_id'), 'usage_limits', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_usage_limits_user_id'), 'usage_limits', ['user_id'], unique=False)
    op.create_table('usage_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_units', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_summaries_id'), 'usage_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_usage_summaries_organisation_id'), 'usage_summaries', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_usage_summaries_user_id'), 'usage_summaries', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('billing_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('usage_event_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('invoice_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('billing_period_start', sa.DateTime(), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('billed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['usage_event_id'], ['usage_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_billing_records_id'), 'billing_records', ['id'], unique=False)
    op.create_index(op.f('ix_billing_records_organisation_id'), 'billing_records', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_billing_records_usage_event_id'), 'billing_records', ['usage_event_id'], unique=False)
    op.create_index(op.f('ix_billing_records_user_id'), 'billing_records', ['user_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('scoring_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_decisions_decision'), 'decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_organisation_id'), 'decisions', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_decisions_risk_score'), 'decisions', ['risk_score'], unique=False)
    op.create_index(op.f('ix_decisions_transaction_id'), 'decisions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_decisions_user_id'), 'decisions', ['user_id'], unique=False)
    op.create_table('limit_usage_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usage_limit_id', sa.Integer(), nullable=False),
    sa.Column('current_usage', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usage_limit_id'], ['usage_limits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_limit_usage_records_id'), 'limit_usage_records', ['id'], unique=False)
    op.create_index(op.f('ix_limit_usage_records_usage_limit_id'), 'limit_usage_records', ['usage_limit_id'], unique=False)
    op.create_table('review_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cases_created_at'), 'review_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_cases_decision_id'), 'review_cases', ['decision_id'], unique=True)
    op.create_index(op.f('ix_review_cases_id'), 'review_cases', ['id'], unique=False)
    op.create_index(op.f('ix_review_cases_organisation_id'), 'review_cases', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_review_cases_resolution'), 'review_cases', ['resolution'], unique=False)
    op.create_index(op.f('ix_review_cases_resolved_at'), 'review_cases', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_review_cases_status'), 'review_cases', ['status'], unique=False)
    op.create_index(op.f('ix_review_cases_transaction_id'), 'review_cases', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_review_cases_user_id'), 'review_cases', ['user_id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['fraud_rules.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_created_at'), 'risk_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_signals_decision_id'), 'risk_signals', ['decision_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_id'), 'risk_signals', ['id'], unique=False)
    op.create_index(op.f('ix_risk_signals_organisation_id'), 'risk_signals', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_reason_code'), 'risk_signals', ['reason_code'], unique=False)
    op.create_index(op.f('ix_risk_signals_rule_code'), 'risk_signals', ['rule_code'], unique=False)
    op.create_index(op.f('ix_risk_signals_rule_id'), 'risk_signals', ['rule_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_transaction_id'), 'risk_signals', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_user_id'), 'risk_signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_signals_user_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_transaction_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_rule_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_rule_code'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_reason_code'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_organisation_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_decision_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_created_at'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_review_cases_user_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_transaction_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_status'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_resolved_at'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_resolution'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_organisation_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_decision_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_created_at'), table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index(op.f('ix_limit_usage_records_usage_limit_id'), table_name='limit_usage_records')
    op.drop_index(op.f('ix_limit_usage_records_id'), table_name='limit_usage_records')
    op.drop_table('limit_usage_records')
    op.drop_index(op.f('ix_decisions_user_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_transaction_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_risk_score'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_organisation_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_billing_records_user_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_usage_event_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_organisation_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_id'), table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_usage_summaries_user_id'), table_name='usage_summaries')
    op.drop_index(op.f('ix_usage_summaries_organisation_id'), table_name='usage_summaries')
    op.drop_index(op.f('ix_usage_summaries_id'), table_name='usage_summaries')
    op.drop_table('usage_summaries')
    op.drop_index(op.f('ix_usage_limits_user_id'), table_name='usage_limits')
    op.drop_index(op.f('ix_usage_limits_organisation_id'), table_name='usage_limits')
    op.drop_index(op.f('ix_usage_limits_limit_type'), table_name='usage_limits')
    op.drop_index(op.f('ix_usage_limits_id'), table_name='usage_limits')
    op.drop_table('usage_limits')
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_organisation_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_event_type'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_method'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_organisation_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_email'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_currency'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_channel'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organisation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('idx_audit_lookup', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organisation_settings_organisation_id'), table_name='organisation_settings')
    op.drop_index(op.f('ix_organisation_settings_id'), table_name='organisation_settings')
    op.drop_table('organisation_settings')
    op.drop_index(op.f('ix_fraud_rules_rule_code'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_reason_code'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_priority'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_organisation_id'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_operator'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_id'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_field_name'), table_name='fraud_rules')
    op.drop_index(op.f('ix_fraud_rules_enabled'), table_name='fraud_rules')
    op.drop_table('fraud_rules')
    op.drop_index(op.f('ix_billing_plans_organisation_id'), table_name='billing_plans')
    op.drop_index(op.f('ix_billing_plans_id'), table_name='billing_plans')
    op.drop_table('billing_plans')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_organisations_slug'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_ip_geolocations_ip_start'), table_name='ip_geolocations')
    op.drop_index(op.f('ix_ip_geolocations_ip_end'), table_name='ip_geolocations')
    op.drop_index(op.f('ix_ip_geolocations_id'), table_name='ip_geolocations')
    op.drop_index(op.f('ix_ip_geolocations_country_code'), table_name='ip_geolocations')
    op.drop_table('ip_geolocations')
    op.drop_index(op.f('ix_bin_lookups_id'), table_name='bin_lookups')
    op.drop_index(op.f('ix_bin_lookups_bin_number'), table_name='bin_lookups')
    op.drop_table('bin_lookups')
    # ### end Alembic commands ###
